[package]
name = "simd"
version = "0.1.0"
authors = ["Huon Wilson <dbau.pp+github@gmail.com>"]

[dependencies]
rustc-serialize = "0.3.2"

serde = { version = "0.4", optional = true }
serde_macros = { version = "0.4", optional = true }
